### ISSUE TITLE
java.lang.VerifyError: Bad access to protected data in getfield

### ISSUE THREAD

**Issue by jena-s-lab** [kitsushadow/forgecraft-issues#8]
https://gist.github.com/kane-thornwyrd/4f8d03efc829b6f8430ab84e08950bea

**Comment by jena-th** [comment]
Resolved by installing CraftTweaker 2 4.1.19. So that's just an invisible dependency, nothing serious.

Edit: nope, it seems more like a workaround, but at least it provide a quick fix for those who need ForgeCraft to work asap !

**Comment by jena-th** [comment]
Thank you Kitsune this is a really great mod that only suffer some communication errors and mostly PEBCAK.
